### ISSUE TITLE
missing global update for new people joining the world.

### ISSUE THREAD

**Issue by Macfhearguis** [DomNomNomVR/cvr-audio-link#2] opened 2022-09-11 23:48 UTC
When someone joins the world they load of the default settings of the audio link controllers.
Current fix for this is having someone click once on everything to update every part of the controller to new players joining the world.

Would be nice to either have a force update button where you can manually force update everything for when new people join the world.

If there is no other way of having the game itself gather said information when they join.

**Comment by DomNomNomVR** [comment] 2022-09-13 10:52
Having a look now. Seems to reproduce on the latest version.

**Comment by DomNomNomVR** [comment] 2022-09-13 12:07
Turns out it's an easy fix but finding what was missing was a bit tricky
![image](https://user-images.githubusercontent.com/108088541/189895630-4a0b4041-c439-43be-881b-93f4a46b1e73.png)
https://developers.abinteractive.net/cck/components/interactable/

**Comment by Macfhearguis** [comment] 2022-09-13 12:09
oooo cool if thats all there is to it ill just change it right now in my own world.

**Comment by DomNomNomVR** [comment] 2022-09-13 13:05
Alrighty, pushed a fix; planning on bundling a release tomorrow.

**Closed as completed** 2022-09-18 13:16 UTC
